#ifndef ARRAY_TOKEN_HPP
#define ARRAY_TOKEN_HPP

enum class ArrayToken { LENGTH, PUSH, POP, SHIFT, UNSHIFT, SPLICE, SLICE, CONCAT, JOIN, REVERSE, SORT, MAP, FILTER, REDUCE, INCLUDES, FOR_EACH, INDEX_OF };

#endif