#ifndef DATA_TOKEN_HPP
#define DATA_TOKEN_HPP

enum class DataToken {
  SET_FUNCTION_IDENTIFIER,
  SET_VARIABLE_IDENTIFIER,
  SET_CONSTANT_IDENTIFIER,
  USE_FUNCTION_IDENTIFIER,
  USE_VARIABLE_IDENTIFIER,
  USE_CONSTANT_IDENTIFIER,
  STRING_LITERAL,
  INTEGER_LITERAL,
  DOUBLE_LITERAL
};

#endif