#ifndef DATA_TOKEN_HPP
#define DATA_TOKEN_HPP

enum class DataToken {
  COMMENT_LITERAL,
  STRING_LITERAL,
  CHAR_LITERAL,
  BOOLEAN_LITERAL,
  HEX_CODE_LITERAL,
  INTEGER_LITERAL,
  DOUBLE_LITERAL,
  NULL_LITERAL,
  IDENTIFIER
};

#endif // DATA_TOKEN_HPP