#ifndef OPERATOR_TOKEN_HPP
#define OPERATOR_TOKEN_HPP

enum class OperatorToken {
  ASSIGN,
  ADDITION,
  SUBTRACTION,
  MULTIPLICATION,
  DIVISION,
  MODULUS,
  ADDITION_ASSIGNMENT,
  SUBTRACTION_ASSIGNMENT,
  MULTIPLICATION_ASSIGNMENT,
  DIVISION_ASSIGNMENT,
  MODULUS_ASSIGNMENT,
  INCREMENT,
  DECREMENT,
  POTENTIATION
};

#endif  // OPERATOR_TOKEN_HPP