name: sQeeZ-Interpreter-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ make cmake clang-format python3-pip

    - name: Install cpplint
      run: pip3 install cpplint

    - name: Check code style with clang-format
      run: |
        for file in $(find . -name '*.cpp' -o -name '*.h'); do
          clang-format -style=file -output-replacements-xml $file | grep -c "<replacement " > /dev/null
          if [ $? -ne 1 ]; then
            echo "Code style issues found in file: $file"
            exit 1
          fi
        done

    - name: Check code style with cpplint
      run: |
        cpplint $(find . -name '*.cpp' -o -name '*.hpp')

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build/test
        ctest
