name: sQeeZ-Interpreter-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make cmake clang-format python3-pip
        pip3 install cpplint

    - name: Check code style with clang-format
      run: |
        files=$(find . -name '*.cpp' -o -name '*.hpp')
        found_issues=0
        for file in $files; do
          result=$(clang-format -style=file -output-replacements-xml "$file")
          num_replacements=$(echo "$result" | grep -c "<replacement ")
          if [ $num_replacements -gt 0 ]; then
            echo "Code style issues found in file: $file"
            found_issues=1
          fi
        done
        if [ $found_issues -eq 1 ]; then
          exit 1
        fi

    - name: Check code style with cpplint
      run: |
        cpplint $(find . -name '*.cpp' -o -name '*.hpp')

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build/test
        ctest
