#ifndef TOKEN_HPP
#define TOKEN_HPP

enum class TokenType {
    TOKEN_EOF,
    // Keywords
    TOKEN_IF,
    TOKEN_ELSE,
    TOKEN_ELSE_IF,
    TOKEN_FOR,
    TOKEN_IN,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_RETURN,
    TOKEN_FUNCTION,
    TOKEN_LET,
    TOKEN_CONST,
    // Operators
    TOKEN_ADDITION,
    TOKEN_SUBTRACTION,
    TOKEN_MULTIPLICATION,
    TOKEN_DIVISION,
    TOKEN_MODULUS,
    TOKEN_ADDITION_ASSIGNMENT,
    TOKEN_SUBTRACTION_ASSIGNMENT,
    TOKEN_MULTIPLICATION_ASSIGNMENT,
    TOKEN_DIVISION_ASSIGNMENT,
    TOKEN_MODULUS_ASSIGNMENT,
    TOKEN_INCREMENT,
    TOKEN_DECREMENT,
    TOKEN_POTENTIATION,
    TOKEN_FLOOR_DIVISION,
    // Logical
    TOKEN_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_GREATER_EQUAL,
    TOKEN_LESS_EQUAL,
    TOKEN_AND,
    TOKEN_OR,
    TOKEN_NOT,
    // Log
    TOKEN_LOG_COLORED,
    TOKEN_LOG_BASIC,
    TOKEN_LOG_ERROR,
    // Unknown
    TOKEN_UNKNOWN
};

struct Token {
    TokenType type;
    std::string value;
};

#endif
